strap_node:
    ros__parameters:
        # define global variables
        delta_t : 0.01

        # INS/GPS variances
        pos_std : 5                         # m
        h_std : 7                           # m
        vel_std : 0.25                      # m/s
        att_std : 0.017453292           # deg
        bias_std : 9.81e-3              # mg
        drift_std : 0.00000484813  # deg/hr

        tau_i : 0.2
        tau_bad : 0.2

        sigma_ra : 9.81e-3                # mg
        sigma_rg : 0.00000484813        # deg / hr
        sigma_bad : 19.62e-3               # mg
        sigma_bgd : 0.00002424068  # deg / hr

ins_gps_node:
    ros__parameters:
        # define global variables
        delta_t : 0.01

        # INS/GPS variances
        pos_std : 5                         # m
        h_std : 7                           # m
        vel_std : 0.25                      # m/s
        att_std : 0.017453292           # deg
        bias_std : 9.81e-3              # mg
        drift_std : 0.00000484813  # deg/hr

        tau_i : 0.2
        tau_bad : 0.2

        sigma_ra : 9.81e-3                # mg
        sigma_rg : 0.00000484813        # deg / hr
        sigma_bad : 19.62e-3               # mg
        sigma_bgd : 0.00002424068  # deg / hr
